### ISSUE TITLE
Wrong language

### ISSUE THREAD

**Issue by nambpgh** [achtnullzwei/A1TV_EPG#14]
The XML tags `display-name` for `channels` and `title`, `sub-title` and `category` for `programme` have a `lang` attribute and the language is set to `en`.

There is no language in the A1 API and the language is set hardcoded in `functions.py` (`generate_xmltv`).

```
    <display-name lang="en">A1 Now HD</display-name>
    <display-name lang="en">ORF 1</display-name>
    <display-name lang="en">ORF 2 W</display-name>
...
  <programme channel="ServusTV" start="20200413003500 +0000" stop="20200413023000 +0000">
    <title lang="en">Echte Wiener 2 - Die Deppat'n und die Gspritzt'n</title>
    <sub-title lang="en">--</sub-title>
    <date>2010</date>
    <category lang="en">Sendung</category>
    <category lang="en">Komödie</category>
  </programme>
```

Since the data from the A1 API are basically in German, `de` should be used (or even the `lang` attribute might be omitted, since the `lang` attribute is optional).

**Comment by achtnullzwei** [comment]
Added to latest pull request and merged to master. :-)
