### ISSUE TITLE
Missing sub-title results in "--"

### ISSUE THREAD

**Issue by nambpgh** [achtnullzwei/A1TV_EPG#15]
If there is no sub-title in the JSON data, it will be set to `--` (`load_epg` in `functions.py`).

```
  <programme channel="ServusTV" start="20200413003500 +0000" stop="20200413023000 +0000">
    <title lang="en">Echte Wiener 2 - Die Deppat'n und die Gspritzt'n</title>
    <sub-title lang="en">--</sub-title>
    <date>2010</date>
    <category lang="en">Sendung</category>
    <category lang="en">Komödie</category>
  </programme>
```

Since the `sub-title` is optional in the [DTD](https://github.com/XMLTV/xmltv/blob/master/xmltv.dtd) it might be better not to write the `sub-title` element, if there is no sub-title in the data.

**Comment by achtnullzwei** [comment]
Added to latest pull request and merged to master. :-)
