### ISSUE TITLE
Bug: Not working any more (new stations "A1 TV Plus Promo")

### ISSUE THREAD

**Issue by nambpgh** [achtnullzwei/A1TV_EPG#20]
The software is not working any more for me (since today)
I'll get an error.
I'm currently not on my machine but it's a Python error, a key error (I think at line 123 api.py).
The problem seems to be because of a new station: "A1 TV Plus Promo" (number 994).

I can _not_ find a workaround (e.g. switch profile, update channel list).

**Comment by achtnullzwei** [comment]
I saw it. A1 seemed to have changed something in one part of the API but not consistently. I will try to figure it out and fix it in the evening.

**Comment by achtnullzwei** [comment]
Fixed.

**Comment by nambpgh** [comment]
Tested: OK!
Thx for quick fixing.

P.S.: I think, I have to learn/improve my Python skills. I can just read it but my first try to fix it failed.
